apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: center-ingress
  labels:
    app: studentapp
spec:
  ingressClassName: nginx 
  rules:
  - host: <Host>
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: <Service>
            port: 
              number: <Port>
