apiVersion: v1
kind: Service
metadata: 
   name: studentapp-frontend-svc
   labels:
      app: studentapp
spec:
   selector:
      app: studentapp-frontend-deploy    
   ports: 
       - port: 80 
         targetPort: 80     