server.port=8080
spring.datasource.url=jdbc:mariadb://database-1.cl888maswxb0.ap-south-1.rds.amazonaws.com:3306/studentapp
spring.datasource.username=omkar
spring.datasource.password=omkar123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



