apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: studentapp-db-hpa
  labels:
    app: studentapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: studentapp-db
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
